-- ============================================================
-- Car Rental Service — Schema (Oracle 23ai port)
-- ============================================================
-- Port of test_app_db/init/01_schema.sql. The two schemas are kept
-- deliberately identical in table names, column names, column order and
-- constraint semantics, so that the Oracle and PostgreSQL arms of the
-- evaluation differ only by SQL dialect and tooling — not by data model.
--
-- Type mapping applied:
--   SERIAL            -> NUMBER GENERATED BY DEFAULT AS IDENTITY
--                        (BY DEFAULT, not ALWAYS: the seed data is replayed
--                        from PostgreSQL with explicit ids so both databases
--                        hold identical rows, which requires inserting into
--                        the identity column.)
--   VARCHAR(n)        -> VARCHAR2(n)
--   TEXT              -> CLOB
--   NUMERIC(10,2)     -> NUMBER(10,2)
--   INTEGER           -> NUMBER(10)
--   BOOLEAN           -> NUMBER(1) + CHECK (0,1)   (no portable BOOLEAN pre-23ai)
--   NOW()             -> SYSTIMESTAMP
--   CURRENT_DATE      -> SYSDATE
--   ON DELETE RESTRICT-> omitted (Oracle's default no-action IS restrict)
--
-- ONE DELIBERATE DEVIATION: reviews.comment is named reviews.comment_text
-- here. COMMENT is an Oracle reserved word and cannot be used as an
-- identifier unquoted. Quoting it ("COMMENT") would force every generated
-- query to quote it too, and models routinely forget — which would depress
-- Oracle accuracy for a reason unrelated to what this thesis measures.
-- Renaming keeps the comparison clean. Both engines are introspected before
-- prompting, so each arm sees the name that actually exists.

-- 1. Locations (branch offices)
CREATE TABLE car_rental.locations (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    city        VARCHAR2(100) NOT NULL,
    address     VARCHAR2(255) NOT NULL,
    phone       VARCHAR2(20),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 2. Employees
CREATE TABLE car_rental.employees (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id NUMBER(10) NOT NULL REFERENCES car_rental.locations(id) ON DELETE CASCADE,
    first_name  VARCHAR2(50) NOT NULL,
    last_name   VARCHAR2(50) NOT NULL,
    role        VARCHAR2(30) NOT NULL CHECK (role IN ('manager', 'agent', 'mechanic', 'receptionist')),
    salary      NUMBER(10,2) NOT NULL,
    hire_date   DATE NOT NULL,
    email       VARCHAR2(150),
    phone       VARCHAR2(20),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 3. Vehicle categories
CREATE TABLE car_rental.vehicle_categories (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(50) NOT NULL UNIQUE,
    description     CLOB,
    daily_rate_min  NUMBER(10,2) NOT NULL,
    daily_rate_max  NUMBER(10,2) NOT NULL
);

-- 4. Vehicles
CREATE TABLE car_rental.vehicles (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     NUMBER(10) NOT NULL REFERENCES car_rental.vehicle_categories(id),
    location_id     NUMBER(10) NOT NULL REFERENCES car_rental.locations(id) ON DELETE CASCADE,
    make            VARCHAR2(50) NOT NULL,
    model           VARCHAR2(50) NOT NULL,
    year            NUMBER(10) NOT NULL CHECK (year BETWEEN 2015 AND 2025),
    license_plate   VARCHAR2(20) NOT NULL UNIQUE,
    color           VARCHAR2(30),
    daily_rate      NUMBER(10,2) NOT NULL,
    mileage         NUMBER(10) DEFAULT 0 NOT NULL,
    status          VARCHAR2(20) DEFAULT 'available' NOT NULL
                        CHECK (status IN ('available', 'rented', 'maintenance', 'retired')),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 5. Clients (customers)
CREATE TABLE car_rental.clients (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR2(50) NOT NULL,
    last_name           VARCHAR2(50) NOT NULL,
    email               VARCHAR2(150) NOT NULL UNIQUE,
    phone               VARCHAR2(20),
    drivers_license     VARCHAR2(30) NOT NULL,
    date_of_birth       DATE NOT NULL,
    registration_date   DATE DEFAULT SYSDATE NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 6. Reservations
CREATE TABLE car_rental.reservations (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       NUMBER(10) NOT NULL REFERENCES car_rental.clients(id) ON DELETE CASCADE,
    vehicle_id      NUMBER(10) NOT NULL REFERENCES car_rental.vehicles(id) ON DELETE CASCADE,
    pickup_location NUMBER(10) NOT NULL REFERENCES car_rental.locations(id) ON DELETE CASCADE,
    return_location NUMBER(10) NOT NULL REFERENCES car_rental.locations(id),
    pickup_date     DATE NOT NULL,
    return_date     DATE NOT NULL,
    status          VARCHAR2(20) DEFAULT 'confirmed' NOT NULL
                        CHECK (status IN ('confirmed', 'active', 'completed', 'cancelled', 'no_show')),
    total_cost      NUMBER(10,2),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT chk_dates CHECK (return_date >= pickup_date)
);

-- 7. Payments
CREATE TABLE car_rental.payments (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  NUMBER(10) NOT NULL REFERENCES car_rental.reservations(id) ON DELETE CASCADE,
    amount          NUMBER(10,2) NOT NULL,
    payment_method  VARCHAR2(20) NOT NULL
                        CHECK (payment_method IN ('credit_card', 'debit_card', 'cash')),
    payment_date    DATE NOT NULL,
    status          VARCHAR2(20) DEFAULT 'completed' NOT NULL
                        CHECK (status IN ('completed', 'pending', 'refunded', 'failed')),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 8. Maintenance records
CREATE TABLE car_rental.maintenance_records (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id      NUMBER(10) NOT NULL REFERENCES car_rental.vehicles(id) ON DELETE CASCADE,
    maintenance_type VARCHAR2(30) NOT NULL
                        CHECK (maintenance_type IN ('oil_change', 'tire_rotation', 'brake_service',
                                                     'general_inspection', 'engine_repair', 'body_repair',
                                                     'transmission', 'ac_service', 'battery_replacement')),
    description     CLOB,
    cost            NUMBER(10,2) NOT NULL,
    maintenance_date DATE NOT NULL,
    mileage_at_service NUMBER(10),
    completed       NUMBER(1) DEFAULT 1 CHECK (completed IN (0, 1)),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 9. Reviews
CREATE TABLE car_rental.reviews (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  NUMBER(10) NOT NULL REFERENCES car_rental.reservations(id) ON DELETE CASCADE,
    rating          NUMBER(10) NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment_text    CLOB,
    review_date     DATE NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Indexes for common query patterns.
-- Oracle creates indexes for PRIMARY KEY and UNIQUE automatically, so only
-- the non-constraint indexes from the PostgreSQL schema are recreated here.
CREATE INDEX car_rental.idx_reservations_client      ON car_rental.reservations(client_id);
CREATE INDEX car_rental.idx_reservations_vehicle     ON car_rental.reservations(vehicle_id);
CREATE INDEX car_rental.idx_reservations_pickup_date ON car_rental.reservations(pickup_date);
CREATE INDEX car_rental.idx_reservations_status      ON car_rental.reservations(status);
CREATE INDEX car_rental.idx_payments_reservation     ON car_rental.payments(reservation_id);
CREATE INDEX car_rental.idx_vehicles_category        ON car_rental.vehicles(category_id);
CREATE INDEX car_rental.idx_vehicles_location        ON car_rental.vehicles(location_id);
CREATE INDEX car_rental.idx_employees_location       ON car_rental.employees(location_id);
CREATE INDEX car_rental.idx_reviews_reservation      ON car_rental.reviews(reservation_id);
CREATE INDEX car_rental.idx_maintenance_vehicle      ON car_rental.maintenance_records(vehicle_id);
